In [3]:
import pickle
import numpy as np

In [5]:
ohe_sex = pickle.load(open('/content/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('/content/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('/content/clf.pkl', 'rb'))

In [7]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
# test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [30]:
# custom input

pclass = int(input('enter your pclass (1/2/3): '))
gender = input('enter your gender (male/female): ')
age = float(input('enter your age: '))
sibsp = int(input('enter your sibling with you(1 to 6): '))
parch = int(input('enter your parents with you: '))
fare = float(input('enter your fare:'))
embarked = input('enter your embarked(S/Q/C)')

test_input = np.array([pclass, gender, age, sibsp, parch, fare, embarked],dtype=object).reshape(1,7)

enter your pclass (1/2/3): 2
enter your gender (male/female): male
enter your age: 31
enter your sibling with you(1 to 6): 0
enter your parents with you: 0
enter your fare:10.5
enter your embarked(S/Q/C)S


In [31]:
test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1,1))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [32]:
test_input_sex

array([[0., 1.]])

In [33]:
test_input_embarked = ohe_embarked.transform(test_input[:, -1].reshape(1,1))

In [34]:
test_input_embarked

array([[0., 0., 1.]])

In [35]:
test_input_age = test_input[:, 2].reshape(1,1)

In [36]:
test_input_age

array([[31.0]], dtype=object)

In [37]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]], test_input_age, test_input_sex, test_input_embarked), axis=1)

In [38]:
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [21]:
test_input_transformed.shape

(1, 10)

In [39]:
clf.predict(test_input_transformed)

array([1])

In [27]:
# import pandas as pd
# df = pd.read_csv('train.csv')

In [29]:
# df.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
363,364,0,3,"Asim, Mr. Adola",male,35.0,0,0,SOTON/O.Q. 3101310,7.0500,NaN,S
464,465,0,3,"Maisner, Mr. Simon",male,NaN,0,0,A/S 2816,8.0500,NaN,S
790,791,0,3,"Keane, Mr. Andrew ""Andy""",male,NaN,0,0,12460,7.7500,NaN,Q
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
47,48,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN,Q
298,299,1,1,"Saalfeld, Mr. Adolphe",male,NaN,0,0,19988,30.5000,C106,S
589,590,0,3,"Murdlin, Mr. Joseph",male,NaN,0,0,A./5. 3235,8.0500,NaN,S
414,415,1,3,"Sundman, Mr. Johan Julian",male,44.0,0,0,STON/O 2. 3101269,7.9250,NaN,S
192,193,1,3,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19.0,1,0,350046,7.8542,NaN,S
817,818,0,2,"Mallet, Mr. Albert",male,31.0,1,1,S.C./PARIS 2079,37.0042,NaN,C
